name: FoodBuddy
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.2
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    GENERATE_INFOPLIST_FILE: NO
targets:
  FoodBuddy:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: FoodBuddy
    info:
      path: FoodBuddy/App/Info.plist
      properties:
        NSCameraUsageDescription: FoodBuddy needs camera access to capture meal photos.
        NSPhotoLibraryUsageDescription: FoodBuddy needs photo library access to import meal photos.
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.igorkupczynski.foodbuddy
        PRODUCT_NAME: FoodBuddy
        INFOPLIST_FILE: FoodBuddy/App/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: YES
        CODE_SIGN_ENTITLEMENTS: FoodBuddy/App/FoodBuddy.entitlements
        CODE_SIGNING_ALLOWED: YES
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED[sdk=macosx*]: NO

  FoodBuddyDev:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: FoodBuddy
    info:
      path: FoodBuddy/App/Info.plist
      properties:
        NSCameraUsageDescription: FoodBuddy needs camera access to capture meal photos.
        NSPhotoLibraryUsageDescription: FoodBuddy needs photo library access to import meal photos.
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: info.kupczynski.foodbuddy.dev
        PRODUCT_NAME: FoodBuddy Dev
        INFOPLIST_FILE: FoodBuddy/App/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: YES
        CODE_SIGN_ENTITLEMENTS:
        CODE_SIGNING_ALLOWED: YES
        CODE_SIGNING_REQUIRED: YES
        DEVELOPMENT_TEAM:

  FoodBuddyCoreTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: FoodBuddy/Domain
      - path: FoodBuddy/Storage
      - path: FoodBuddy/Services
      - path: FoodBuddy/Support/PlatformImage.swift
      - path: FoodBuddy/Features/Capture/CaptureIngestCoordinator.swift
      - path: FoodBuddyCoreTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.igorkupczynski.foodbuddy.coretests
        PRODUCT_NAME: FoodBuddyCoreTests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  FoodBuddyUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: FoodBuddyUITests
    dependencies:
      - target: FoodBuddy
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.igorkupczynski.foodbuddy.uitests
        PRODUCT_NAME: FoodBuddyUITests
        TEST_TARGET_NAME: FoodBuddy
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

schemes:
  FoodBuddy:
    build:
      targets:
        FoodBuddy: all
        FoodBuddyCoreTests: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: FoodBuddyCoreTests
    run:
      config: Debug

  FoodBuddyDev:
    build:
      targets:
        FoodBuddyDev: all
        FoodBuddyCoreTests: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: FoodBuddyCoreTests
    run:
      config: Debug

  FoodBuddyUITests:
    build:
      targets:
        FoodBuddy: all
        FoodBuddyUITests: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: FoodBuddyUITests
    run:
      config: Debug
